# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
# To manually select a Xamarin SDK version on the Microsoft-hosted macOS agent,
# configure this task with the *Mono* version that is associated with the
# Xamarin SDK version that you need, and set the "enabled" property to true.
# See https://go.microsoft.com/fwlink/?linkid=871629
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
  displayName: 'Select the Xamarin SDK version'
  enabled: false

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'Tensorflow.Lite.Net/Tensorflow.Lite.Net.iOS.csproj'

- task: MSBuild@1
  inputs:
    solution: 'Tensorflow.Lite.Net/Tensorflow.Lite.Net.iOS.csproj'
    configuration: 'Release'
- task: CmdLine@2
  inputs:
    script: 'ls ./'
- task: CmdLine@2
  inputs:
    script: 'ls ./Tensorflow.Lite.Net.iOS'
- task: CmdLine@2
  inputs:
    script: 'ls ./Tensorflow.Lite.Net.iOS/bin'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- publish: Tensorflow.Lite.Net.iOS/bin/Release/
  artifact: iosDlls